#!/usr/bin/env bash

set -e

# Sort ag results by last modified timestamp descending and line number ascending
ag --nogroup $@ \
| awk -F: '{ "date -r "$1" +%s" | getline d; print d":"$0; close("date -r "$1" +%s") }' \
| sort -t: -k 1,2r -k 3,4n \
| cut -f 2- -d ':'

